import {
    PayPalScriptProvider,
    BraintreePayPalButtons,
} from "@paypal/react-paypal-js";

import axios from 'axios'

export default function Pay() {
    return (
        <>
            <PayPalScriptProvider
                options={{
                    clientId: "test",
                    dataClientToken:
                        "<the data-client-token value generated by your server-side code>",
                }}
            >
                <BraintreePayPalButtons
                    createOrder={(data, actions) => {
                        return actions.braintree.createPayment({
                            flow: "checkout",
                            amount: "10.0",
                            currency: "USD",
                            intent: "capture",
                        });
                    }}
                    onApprove={(data, actions) => {
                        return actions.braintree
                            .tokenizePayment(data)
                            .then((payload) => {
                                // call server-side endpoint to finish the sale
                            });
                    }}
                />
            </PayPalScriptProvider>
        </>
    )
}